[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn backend.rag_backend:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[build.env]
PYTHON_VERSION = "3.11" 